# Generated by Django 5.1.2 on 2024-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloans', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_issued',
            field=models.DateField(),
        ),
    ]
